### ISSUE TITLE
X_val, y_val = validation_data(0), validation_data(1)

### ISSUE THREAD

**Issue by lmassaron** [DataCanvasIO/deeptables#12]
On deeptable.py there is a line:

X_val, y_val = validation_data(0), validation_data(1)

which should instead be:

X_val, y_val = validation_data[0], validation_data[1]

or when you fit a model with a validation sample, the API won't accept as input any list or tuple of validation data and target.

**Comment by gladomat** [comment]
This has been fixed in the latest pacakge.
