### ISSUE TITLE
How do I pass task='regression' to DeepTable'?

### ISSUE THREAD

**Issue by gladomat** [DataCanvasIO/deeptables#13]
I haven't figure out how to pass the task which I want done to `DeepTable`. I saw that I can pass it to `DeepModel(task='regression')`. However, I want to pass it to `DeepTalbe`.

Edit: The reason I want to do this is that the auto-task categorizes the task as a multiclass classification if I pass ints as y, and the number of classes < 1000 (which they are in my case). I could, of course, convert the ints to float32, but I want the control over the model directly.

**Comment by jackguagua** [comment]
@gladomat Not supported yet, we will improve it as soon as possible.Thank you very much for your suggestions!

**Comment by oaksharks** [comment]
@gladomat @jackguagua you can set it in `ModelConfig` now just like：
```
config = deeptable.ModelConfig(nets=deepnets.DeepFM, auto_discrete=True,  task='regression', metrics=['MAE'])
dt = deeptable.DeepTable(config=config)

model, history = dt.fit(df_train, y, epochs=2)
```

The optional values for the attribute `task` are:
-  'auto' (as default value, infer from dataset .) 
-  'binary'
-  'multiclass'
-  'regression'

Update code from master branch and try again, good luck !
