### ISSUE TITLE
some bugs in CategoricalFocalLoss function

### ISSUE THREAD

**Issue by CyrilZhao-sudo** [DataCanvasIO/DeepTables#20]
super(**BinaryFocalLoss,** self).__init__(reduction=reduction, name=name)  
the BinaryFocalLoss may be CategoricalFocalLoss

**Comment by jackguagua** [comment]
@CyrilZhao-sudo  This is fixed now, thanks.

**Comment by CyrilZhao-sudo** [comment]
> @CyrilZhao-sudo This is fixed now, thanks.

For the layer，MultiheadAttention， the output shape is always (batch_size, field_size, embedding_size), not (batch_size, field_size, embedding_size*num_head). en ?

**Comment by CyrilZhao-sudo** [comment]
> @CyrilZhao-sudo This is fixed now, thanks.

Here, class DefaultPreprocessor,  fit_transform method,            
   {if copy: # TODO  bug here
            X = copy.deepcopy(X)
            y = copy.deepcopy(y)}   .  the copy  may be copy_data.

**Comment by CyrilZhao-sudo** [comment]
> @CyrilZhao-sudo This is fixed now, thanks.

**Comment by CyrilZhao-sudo** [comment]
Here, class DefaultPreprocessor, fit_transform method,
{if copy: # TODO bug here
X = copy.deepcopy(X)
y = copy.deepcopy(y)} . the copy may be copy_data.
