### ISSUE TITLE
DeepTables with Tensorflow 2.2

### ISSUE THREAD

**Issue by mindis** [DataCanvasIO/DeepTables#23]
Hi, 

Would it be possible to use DeepTables with TF v2.2?
If so could you please update requirements and pip distribution.

thanks!

**Comment by jackguagua** [comment]
hi @mindis , there are some changes in the metric names in tf2.2, adaptation work is needed, we will solve it as soon as possible.

**Comment by oaksharks** [comment]
@mindis @jackguagua 
 DT was ready to work with Tensorflow 2.2.0, enjoy it !
