### ISSUE TITLE
Model name always changes when saved

### ISSUE THREAD

**Issue by gladomat** [DataCanvasIO/DeepTables#27]
Is it possible to save the model with a static name? Right now when I save a model multiple times, after every training the model files keep changing. There is the dt.pkl file and another .h5 file. The latter changes its name depending on the ordering of the layers that are in the model. For example, one model might be named `dnn_nets+linear.h5` and after the second training it's called `linear+dnn_nets.h5`. I would love an option where I can set the model name myself.

**Comment by jackguagua** [comment]
@gladomat it's done, now you can set like this:

`
dt.save(filepath, deepmodel_basename='deepmodel')
`

**Comment by gladomat** [comment]
WOW! Amazing! Thank you!

**Comment by gladomat** [comment]
It works from the git repo, so I can close this.
