### ISSUE TITLE
collect problems

### ISSUE THREAD

**Issue by weihong2** [DataCanvasIO/DeepTables#31]
![image](https://user-images.githubusercontent.com/58021131/92340447-f87b4e00-f0ec-11ea-8f3f-50ab7abce862.png)
![image](https://user-images.githubusercontent.com/58021131/92340483-2365a200-f0ed-11ea-803e-755327977b78.png)

**Comment by jackguagua** [comment]
DT中的nets是指一系列的用于特征衍生和提取的网络组件（feature nets/components）或者可以理解为子网络，一个DT的网络主干是由embedding+feature nets + classifier几部分构成的。Models对应近几年一些影响力较大的论文中提出的完整网络架构，比如xDeepFM是由Linear/CIN/Dnn三个网络组合起来的模型，那么在DT中我们提供了十几种不同的子网，这些子网在不同的数据集上通过不同的组合可以实现更好的表现。

**Comment by jackguagua** [comment]
另外DT是一个独立的面向结构化数据的深度学习工具包，和XGBoost、LightGBM这一类算法框架是平行关系，只是为大家提供一个新的选择。
