### ISSUE TITLE
做一个二分类时报错'list' object is  not callable。

### ISSUE THREAD

**Issue by lydia147** [DataCanvasIO/DeepTables#33]
作者您好，我在用example里面做二分类的代码做一个含142个特征的数据集的二分类问题，报错信息是'list' object is  not callable。报错具体为：deepmodel.py的83行和196行；deepmodel.py的358行。可以协助我改一下吗

**Comment by jackguagua** [comment]
感觉是你传入的参数有问题，最好提供一下训练的完整代码

**Comment by lydia147** [comment]
好的，问题已解决，谢谢杨老师！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/DeepTables"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 下午2:01
收件人:&nbsp;"DataCanvasIO/DeepTables"<DeepTables@noreply.github.com&gt;;
抄送:&nbsp;"1501549780"<1501549780@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DataCanvasIO/DeepTables] 做一个二分类时报错'list' object is  not callable。 (#33)





 
感觉是你传入的参数有问题，最好提供一下训练的完整代码

**Comment by jackguagua** [comment]
You are welcome.
