### ISSUE TITLE
Do you have a benchmark for all models?

### ISSUE THREAD

**Issue by diff7** [DataCanvasIO/DeepTables#35]
Hi,
do you have a benchmark for all models?

**Comment by jackguagua** [comment]
There is no benchmark yet, we will consider doing this in the future.

**Comment by diff7** [comment]
Got it, thanks!

I just found this one, of course it is not based on your implementation but still.

https://paperswithcode.com/sota/click-through-rate-prediction-on-criteo

**Comment by jackguagua** [comment]
Thank you for your attention.

**Comment by qo4on** [comment]
Are you going to add MaskNet?

**Comment by jackguagua** [comment]
> Are you going to add MaskNet?

have no plans yet
