### ISSUE TITLE
模型可以聚类吗

### ISSUE THREAD

**Issue by lydia147** [DataCanvasIO/DeepTables#36]
作者您好，看到官网例子上有二分类、多分类和回归，请问有聚类吗?怎么用呢？具体需要设置哪些参数呢?

**Comment by jackguagua** [comment]
感谢您的关注，聚类目前还不支持。

**Comment by lydia147** [comment]
好的，谢谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DataCanvasIO/DeepTables"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 晚上7:26
收件人:&nbsp;"DataCanvasIO/DeepTables"<DeepTables@noreply.github.com&gt;;
抄送:&nbsp;"1501549780"<1501549780@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DataCanvasIO/DeepTables] 模型可以聚类吗 (#36)





 
感谢您的关注，聚类目前还不支持。
