### ISSUE TITLE
DataConversionWarning from example code

### ISSUE THREAD

**Issue by oyvindsam** [DataCanvasIO/DeepTables#38]
Hi, first of all thanks for this library. I am getting a DataConversionWarning from the example in readme:
```
sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
```

on the line `preds = dt.predict(df_test)`. I tried to call it with df_test.values.ravel() which resulted in a 
```ValueError: Number of features of the input must be equal to or greater than that of the fitted transformer. Transformer n_features is 17 and input n_features is 1.```

**Comment by jackguagua** [comment]
You can ignore the warning, it does not affect the results.

**Comment by oyvindsam** [comment]
Ok thanks!
