### ISSUE TITLE
Numpy and Tensorflow: version conflict

### ISSUE THREAD

**Issue by miranska** [DataCanvasIO/DeepTables#48]
During the installation of DeepTables on Python 3.7 using `pip install deeptables`, I get

```
ERROR: tensorflow 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.4 which is incompatible.
```

The installation completes, and the package is working, but I wonder if there are some corner cases where Tensorflow may "explode".

My workaround is to install DeepTables in two steps:

```
pip install tensorflow
pip install deeptables
```

I wonder if there is a better way to get rid of the error permanently.

**Comment by jackguagua** [comment]
@miranska  The dependency on the numpy version has been modified to be consistent with tensorflow. This issue will be fixed in the next release.Thank you for your feedback.

**Comment by miranska** [comment]
Great, thank you!
