### ISSUE TITLE
Bug:  Can't pickle local object during save

### ISSUE THREAD

**Issue by xdssio** [DataCanvasIO/DeepTables#61]
# Can't save model
Somehow, I remember successfuly saving it once before, but it no longer works. 
I've tried to play with the `home_dir` parameter in the config, cleaning it, and using a `tempfile.TemporaryDirectory` but can no longer save my models.

Version: `0.1.14` 
* Tried from pip and from master    

System: `OSX`

Reproduce:
```
from deeptables.models import deeptable
from sklearn.datasets import load_iris

data = load_iris()
X = data['data']
y = data['target']
conf = deeptable.ModelConfig(
        nets=['dnn_nets'],
        metrics=['AUC'],
        optimizer=keras.optimizers.RMSprop(),
    )
dt = deeptable.DeepTable(config=conf)
dt.fit(X, y)
dt.save('model')
```

Error: 
```
Load model from disk:models/dt/dnn_nets.h5.
Traceback (most recent call last):
  File ".../python3.7/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-5a45263f9c71>", line 1, in <module>
    dt.save('model')
  File ".../python3.7/site-packages/deeptables/models/deeptable.py", line 723, in save
    pickle.dump(self, output, protocol=2)
AttributeError: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>'
```

**Comment by xdssio** [comment]
I might have found the issue.
It is the same as [this phygnn issue](https://github.com/NREL/phygnn/issues/16) and they fixed it.

I verified that when I downgraded to `TF 2.3.0`, I managed to save again.

**Comment by oaksharks** [comment]
@xdssio Thanks for your report.
The model is saved including model config (class `deeptable.ModelConfig`), and the optimizer you set `optimizer=keras.optimizers.RMSprop()` in model config cannot be pickled at TF version 2.4.0(in my machine);
You can try to set `optimizer='RMSprop'` if need to use TF 2.4  :
```
from deeptables.models import deeptable
from sklearn.datasets import load_iris

data = load_iris()
X = data['data']
y = data['target']
conf = deeptable.ModelConfig(
        nets=['dnn_nets'],
        metrics=['AUC'],
	# optimizer=keras.optimizers.RMSprop(),
        optimizer='RMSprop',
    )
dt = deeptable.DeepTable(config=conf)
dt.fit(X, y)
dt.save('model')
```
