### ISSUE TITLE
Deepfm 输出概率问题

### ISSUE THREAD

**Issue by liujian329** [DataCanvasIO/DeepTables#63]
deepfm输出为两个维度的数据，需要自己套用逻辑回归算出最终概率吗？
如何根据输出的概率选取TOPN进行召回推荐？谢谢

**Comment by jackguagua** [comment]
主要看你target的选择，如果是分类问题，dt的output会返回正负样本的的概率，你可以用来排序

**Comment by liujian329** [comment]
> 主要看你target的选择，如果是分类问题，dt的output会返回正负样本的的概率，你可以用来排序

DeepFM有三个网络（'linear', 'fm_nets', 'dnn_nets'），但是输出为[[4.0071368e-01 5.9928632e-01]， [9.9921107e-01 7.8889728e-04]]类似的矩阵，请问这个值是哪两个网络的输出？谢谢。

**Comment by liujian329** [comment]
> 主要看你target的选择，如果是分类问题，dt的output会返回正负样本的的概率，你可以用来排序

返回正负样本的概率用加权平均值还是逻辑回归映射到<0,1>区间，进行分数排序？选取最高进行topN排序

**Comment by jackguagua** [comment]
输出的二维向量分别是0，1的概率。这是三个网络add之后的输出，具体网络架构方面可以参考DeepFM的paper https://arxiv.org/pdf/1804.04950.pdf

**Comment by liujian329** [comment]
> 输出的二维向量分别是0，1的概率。这是三个网络add之后的输出，具体网络架构方面可以参考DeepFM的paper https://arxiv.org/pdf/1804.04950.pdf

那简单的说做召回或者排序就是把值为1的概率最大的进行再排序，选择最大概率的input，进行TopN？

**Comment by jackguagua** [comment]
可以这么使用

**Comment by liujian329** [comment]
> > 输出的二维向量分别是0，1的概率。这是三个网络add之后的输出，具体网络架构方面可以参考DeepFM的paper https://arxiv.org/pdf/1804.04950.pdf
> 
> 那简单的说做召回或者排序就是把值为1的概率最大的进行再排序，选择最大概率的input，进行TopN？

![image](https://user-images.githubusercontent.com/80748331/114692828-91410e80-9d4b-11eb-802d-4bc407b1eec0.png)
论文中看到了sigmoid的预测值函数，没有看到正负样本的输出？
