### ISSUE TITLE
deeptables算法的采样策略，GPU和CPU有什么不同

### ISSUE THREAD

**Issue by chendongtian** [DataCanvasIO/DeepTables#70]
CPU和GPU两个版本使用的相同的70W训练数据集，

训练过程中发现日志中使用的训练数据量不一致
cpu使用了5488个样本
gpu使用702439个样本

**Comment by chendongtian** [comment]
![image](https://user-images.githubusercontent.com/86284643/122902769-5974c980-d381-11eb-8a99-3a853f84e34b.png)
![image](https://user-images.githubusercontent.com/86284643/122902874-701b2080-d381-11eb-8058-0cff480bbc8b.png)
![image](https://user-images.githubusercontent.com/86284643/122902972-8aed9500-d381-11eb-99c3-af8cb3fca535.png)
![image](https://user-images.githubusercontent.com/86284643/122903066-a0fb5580-d381-11eb-9248-6b04392c0b87.png)

**Comment by lixfz** [comment]
See https://github.com/tensorflow/tensorflow for more information pls.
