### ISSUE TITLE
Adding tensorboard

### ISSUE THREAD

**Issue by vaibhavsingh007** [DataCanvasIO/DeepTables#76]
This template is for miscellaneous issues not covered by the other issue categories.

Hi, this could be a feature request because I can't find a way to add a tensorboard callback to model. I need to profile a deeptables model for instrumentation.  I'm using deeptables vr 0.2.3.1

Seems this class has a mechanism to inject only early stopping callbacks. Can you please suggest a way I can use tensorboard or add that as a feature in future release? 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/4958034/179596258-dbd95e8a-2175-4d01-9497-096fa5eea175.png">

**Comment by oaksharks** [comment]
Hi @vaibhavsingh007,

Have you tried to pass the TensorBoard callback  to the  `deeptable.DeepTable.fit` method as the following code ? 

```python
config = deeptable.ModelConfig(nets=deepnets.DeepFM, earlystopping_patience=999, apply_class_weight=True, distribute_strategy=distribute_strategy)
dt = deeptable.DeepTable(config=config)

tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir="/tmp/dt_logs/", histogram_freq=1)
# pass `tensorboard_callback` to fit method
model, history = dt.fit(df_train, y, batch_size=batch_size, epochs=epochs, callbacks=[tensorboard_callback])

```

The `__inject_callbacks` does not seem to clear other callbacks, references:

https://github.com/DataCanvasIO/DeepTables/blob/a95f842918351fd1875263490bdddb919de75b20/deeptables/models/deeptable.py#L709-L754

**Comment by vaibhavsingh007** [comment]
Looks like i misread `_inject_callbacks` and thought it's only adding early stopping, which it is, but to all callbacks passed. Thanks for the prompt response @oaksharks . Will try and let you know if there's any issue.

**Comment by vaibhavsingh007** [comment]
Hello @oaksharks, I might need your help with one more thing. I am trying to optimize the input pipeline by prefetching data using `tf.data` API but it looks like `deeptable.fit()` expects X as Pandas or Dask DF, which it then transforms to TF using `to_dataset()`. I understand Deeptables is already fairly optimized however, looks like we can speed up GPU processing by about 10% by using prefetch as per tf profiler. Thoughts?

**Comment by oaksharks** [comment]
I understand that prefetch can reduce the time waiting for data from the data files between two epochs.
Since DeepTables read data from memory as you see it requires a pd.DataFrame,  the effect of using prefetch to accelerate should not be significant.
If you encounter slow loading data when using DeepTables training, you can share the profile data to help find the problem.

References:
1. https://www.tensorflow.org/guide/data_performance_analysis
2. https://www.tensorflow.org/guide/data_performance
3. deeptables.utils.dataset_generator._TFDGForPandas
