### ISSUE TITLE
Error when passing validation_data to dt.fi()

### ISSUE THREAD

**Issue by gladomat** [DataCanvasIO/deeptables#8]
I encountered an error while passing my own validation data to the fit() function. It says that a tuple isn't callable and found this in line 336 in `deeptable.py`:

`X_val, y_val = validation_data(0), validation_data(1)`

I'm not sure what it was supposed to be, but I changed it to square brackets:

`X_val, y_val = validation_data[0], validation_data[1]`

while passing `validation_data=(X_val, y_val)`, and now it works.

**Comment by oaksharks** [comment]
@gladomat Thanks for your report, the bug has been fixed in master branch.
