### ISSUE TITLE
How could I add a custom metric?

### ISSUE THREAD

**Issue by gladomat** [DataCanvasIO/deeptables#9]
I would be interested in adding a custom metric. Could you give me some hints on how to do that? Thanks!

**Comment by jackguagua** [comment]
@gladomat  Good question!
You can see the test case about custom metric: [deeptable_regression_test](https://github.com/DataCanvasIO/deeptables/blob/master/tests/models/deeptable_regression_test.py#L23)

**Comment by gladomat** [comment]
Super, thanks!
