### ISSUE TITLE
How to set random seed 

### ISSUE THREAD

**Issue by hzhz2020** [DataCanvasIO/DeepTables#94]
Dear Authors

Thank you for the nice toolkit. How to set the random seed for reproducibility when using DT models?

dt = DeepTable(config=conf)

Thanks,

**Comment by oaksharks** [comment]
Hi @hzhz2020 ,
Using cross-validation to train the model, the set random_state .
https://github.com/DataCanvasIO/DeepTables/blob/869ca11351eb7a9d4d480e6ba9e92d01961b9f16/deeptables/models/deeptable.py#L373-L379

**Comment by hzhz2020** [comment]
thanks
